export const seats = [
  {
    seatNo: 'PN-E2-4-A-1',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-2',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-3',
    status: 'A',
    allocatedTo: null,
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-4',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-5',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: 'APAC',
  },
  {
    seatNo: 'PN-E2-4-A-6',
    status: 'B',
    allocatedTo: 'APAC',
    amendRequestBy: 'APAC',
  },
  {
    seatNo: 'PN-E2-4-A-1',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-2',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-3',
    status: 'A',
    allocatedTo: null,
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-4',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-5',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: 'APAC',
  },
  {
    seatNo: 'PN-E2-4-A-6',
    status: 'B',
    allocatedTo: 'APAC',
    amendRequestBy: 'APAC',
  },
  {
    seatNo: 'PN-E2-4-A-1',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-2',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-3',
    status: 'A',
    allocatedTo: null,
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-4',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: null,
  },
  {
    seatNo: 'PN-E2-4-A-5',
    status: 'B',
    allocatedTo: 'iCredit',
    amendRequestBy: 'APAC',
  },
  {
    seatNo: 'PN-E2-4-A-6',
    status: 'B',
    allocatedTo: 'APAC',
    amendRequestBy: 'APAC',
  },
];
